#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config window_gap          12
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc rule -a Gimp desktop=^6 follow=on floating=on
bspc rule -a Chromium desktop=^2 follow=on
bspc rule -a Firefox desktop=^2 follow=on
bspc rule -a Blender desktop=^5
bspc rule -a qbittorrent desktop=^10
bspc rule -a gwenview desktop=^3
bspc rule -a thunar desktop=^4
bspc rule -a Steam desktop=^9
bspc rule -a Firefox desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a smplayer floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
panel dzen2 &
feh --bg-fill Pictures/Space/sKbzYFz.jpg
/home/blacx/.config/bspwm/dzenstat | dzen2 -ta r
